"""Compare buem's occupancy-driven electricity/heating/DHW output against
manually-sourced synPRO reference profiles, for household configurations
matching synPRO's own published validation groups (Fischer et al. 2015,
"Model for Electric Load Profiles With High Time Resolution for German
Households" -- Table 2: 1FF single, 2FF couple, 4FF family, all fully
employed).

This is an *indirect* validation, not a reproduction: buem's electricity
profile is generated by the ``occupancy`` package (a Richardson/CREST-style
stochastic occupancy+appliance model), while synPRO uses its own
independently calibrated activity/appliance model from German time-of-use
survey data. The two models are not expected to match exactly -- household
composition, appliance-stock assumptions, and archetype selection differ
between them. What this script checks is whether buem's output falls in a
physically plausible range and has a shape consistent with an
independently validated model, using the same two metrics synPRO's own
paper reports (annual demand and the mean relative error ``Err``, its
Eq. 3) so the numbers are directly comparable to the published values.

Data source
-----------
synPRO's interactive web simulator (https://synpro-lastprofile.de/simulator/)
needs a browser session and, for non-Fraunhofer users, a registration/access
code -- not something this script can drive. Its free, no-login household
profile set (linked from https://synpro-lastprofile.de/gratis-profile,
hosted at https://oc.ise.fraunhofer.de/index.php/s/vmwmRdTPCo2Na1w) is used
instead, checked into ``validation/NL/synpro/reference/`` (CDLA-permissive
2.0, citation required -- see that folder's README PDF):

- ``electric/`` -- 4 household-composition profiles (family-with-children,
  two-full-time-workers, two-over-65, single-under-30), column ``P_el`` [W].
  Envelope-independent (occupancy/appliance driven), so these compare
  against buem's ``elecLoad`` regardless of envelope.
- ``room_heating/`` -- 4 building-envelope profiles (old-building/passive
  house x single/multi-family, fixed occupant counts baked into each file:
  4 for the SFH files, 2 for the MFH files), column ``Q_htg`` [W]. Compares
  against buem's ``heating_load`` -- but a *fair* comparison needs buem run
  against a matching envelope (old-building vs. passive-house U-values),
  which this script does NOT attempt to auto-derive; the default generic
  envelope (see ``_DUMMY_FIXTURE``) is not calibrated to match synPRO's
  German archetypes, so a heating/DHW run against it is indicative of
  plausibility only, not an envelope-matched comparison. Pass
  ``--building-geojson`` with a real matched building to make it one.
- ``domestic_hot_water/`` -- same 4 envelope classes, column ``Q_dhw`` [W].
  Compares against buem's ``dhw_kWh``, same envelope caveat as heating.

Cooling and cooking are NOT testable against synPRO at all: synPRO's
household model doesn't include cooling (residential AC is essentially
absent from the German time-of-use data it's calibrated on), and its
electric total doesn't split cooking out from the other 8 appliance
categories in Table 1 of the paper -- there's no synPRO reference series
for either quantity, at any resolution.

Seed-averaging
--------------
buem's ``elecLoad`` (and the occupancy-driven components of DHW draws /
cooking) is one stochastic realization per run. synPRO's own paper
validates against 100-household group averages (Section 3), not single
realizations -- so a single buem run vs. a single synPRO file will show
near-zero daily correlation even when both models are individually sound,
because two independent random realizations of "when does this household
run its washing machine" don't line up day-to-day. ``--n-seeds`` (default
10) runs buem that many times with different explicit ``seed`` values and
averages the resulting daily profiles before comparing, damping buem's own
realization noise. This does NOT fully close the gap: the synPRO reference
file itself is still a single realization, so some residual noise from
its side remains irreducible with only this free dataset (not fixable
without either synPRO's own paid/registered multi-run output or driving
its interactive simulator, neither available here).

The synPRO export's calendar year (2021) will generally not match whatever
year buem's local weather archive covers (e.g. 2018) -- ``compare()``
therefore aligns the two daily-mean series by day-of-year, not by calendar
date, so this is a seasonal/shape comparison, not a day-for-day one.

Usage::

    python scripts/compare_synpro_vs_buem.py \\
        --quantity electricity \\
        --synpro-dat validation/NL/synpro/reference/electric/synPRO_el_2_fulltime_employees.dat \\
        --num-persons 2 --archetype working_couple --n-seeds 10 \\
        --label 2FF \\
        --csv validation/NL/synpro/synpro_vs_buem_electric.csv

    python scripts/compare_synpro_vs_buem.py \\
        --quantity heating \\
        --synpro-dat validation/NL/synpro/reference/room_heating/synPRO_old_building_single_family_house.dat \\
        --num-persons 4 --n-seeds 10 \\
        --label old_building_SFH \\
        --csv validation/NL/synpro/synpro_vs_buem_heating.csv
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd

from buem.config.building_registry import (
    DEFAULT_LATITUDE,
    DEFAULT_LONGITUDE,
    DEFAULT_WEATHER_PROVIDER,
    DEFAULT_YEAR,
)
from buem.config.cfg_building import CfgBuilding
from buem.integration.scripts.attribute_builder import AttributeBuilder
from buem.integration.scripts.geojson_validator import validate_geojson_request
from buem.thermal.model_buem import ModelBUEM

logger = logging.getLogger(__name__)

# A generic SFH envelope, reused from the repo's own dummy v3 fixture.
# Electricity is occupancy-driven, not envelope-driven, so this is a fair
# stand-in for --quantity electricity. For heating/DHW it is NOT calibrated
# to match synPRO's German old-building/passive-house archetypes -- see
# module docstring -- pass --building-geojson to substitute a real one.
_DUMMY_FIXTURE = (
    Path(__file__).resolve().parent.parent
    / "src" / "buem" / "data" / "buildings" / "dummy" / "building_01_small_residential.json"
)

QUANTITIES = ("electricity", "heating", "dhw")


def _build_geojson_payload(
    *, num_persons: float, archetype: str | None, country: str, building_type: str | None,
    latitude: float, longitude: float, year: int,
    building_geojson: Path | None,
) -> dict:
    source = building_geojson if building_geojson is not None else _DUMMY_FIXTURE
    payload = json.loads(source.read_text(encoding="utf-8"))
    feature = payload["features"][0]
    feature["geometry"]["coordinates"] = [longitude, latitude]
    feature["properties"]["start_time"] = f"{year}-01-01T00:00:00Z"
    feature["properties"]["end_time"] = f"{year + 1}-01-01T00:00:00Z"
    building = feature["properties"]["buem"]["building"]
    building["country"] = country
    building["num_persons"] = num_persons
    if building_type:
        building["building_type"] = building_type
    if archetype:
        building["archetype"] = archetype
    return payload


def _build_attrs(
    *, num_persons: float, archetype: str | None, country: str, building_type: str | None,
    latitude: float, longitude: float, year: int, provider: str, seed: int | None,
    building_geojson: Path | None,
) -> dict:
    payload = _build_geojson_payload(
        num_persons=num_persons, archetype=archetype, country=country, building_type=building_type,
        latitude=latitude, longitude=longitude, year=year,
        building_geojson=building_geojson,
    )
    result = validate_geojson_request(payload)
    if not result.is_valid:
        raise ValueError([str(e) for e in result.get_errors()])
    building_attrs = dict(result.validated_data["features"][0]["properties"]["buem"]["building_attributes"])
    building_attrs["weather_provider"] = provider
    # geojson_validator._convert_v3_to_v2() deliberately never forwards
    # "seed" from a v3 payload (it's an internal reproducibility knob, not
    # part of the EnerPlanET request contract -- see CLAUDE.md), so a
    # per-run seed override has to be injected into the already-converted
    # v2 building_attrs dict directly, after validation, not through the
    # v3 payload above.
    if seed is not None:
        building_attrs["seed"] = seed
    return building_attrs


def run_buem_quantity(
    *, quantity: str, num_persons: float, archetype: str | None, country: str,
    building_type: str | None,
    latitude: float, longitude: float, year: int, provider: str, seed: int | None,
    building_geojson: Path | None,
) -> pd.Series:
    """Runs one buem simulation and returns the requested hourly quantity
    [kW] for a full year.

    ``electricity`` only needs ``AttributeBuilder`` (occupancy generation,
    no thermal solve). ``heating``/``dhw`` need the full
    ``ModelBUEM.sim_model()`` thermal solve -- slower, and see the module
    docstring's envelope-matching caveat for these two.
    """
    building_attrs = _build_attrs(
        num_persons=num_persons, archetype=archetype, country=country, building_type=building_type,
        latitude=latitude, longitude=longitude, year=year, provider=provider,
        seed=seed, building_geojson=building_geojson,
    )
    merged = AttributeBuilder(payload_attrs=building_attrs).build()

    if quantity == "electricity":
        series = merged["elecLoad"]
    elif quantity in ("heating", "dhw"):
        cfg = CfgBuilding(merged).to_cfg_dict()
        model = ModelBUEM(cfg)
        model.sim_model(use_milp=False)
        if quantity == "heating":
            series = pd.Series(np.asarray(model.heating_load, dtype=float), index=cfg["weather"].index)
        else:
            if model.dhw_kWh is None:
                raise RuntimeError("model.dhw_kWh is None -- DHW generation did not run for this building.")
            series = pd.Series(np.asarray(model.dhw_kWh, dtype=float), index=cfg["weather"].index)
    else:
        raise ValueError(f"unknown quantity {quantity!r}, expected one of {QUANTITIES}")

    if not isinstance(series, pd.Series):
        raise TypeError(f"expected a pandas Series for {quantity!r}, got {type(series)}")
    return series


def run_buem_quantity_averaged(*, n_seeds: int, base_seed: int = 1000, **kwargs) -> pd.Series:
    """Runs :func:`run_buem_quantity` ``n_seeds`` times with distinct
    explicit seeds and returns the hour-by-hour mean across runs -- damps
    buem's own single-realization noise before comparing against synPRO's
    (still single-realization) reference. See module docstring."""
    runs = []
    for i in range(n_seeds):
        seed = base_seed + i
        logger.info("  seed %d/%d (seed=%d)", i + 1, n_seeds, seed)
        runs.append(run_buem_quantity(seed=seed, **kwargs))
    aligned = pd.concat(runs, axis=1)
    return aligned.mean(axis=1)


def load_synpro_reference(
    path: Path, *, time_col: str, load_col: str, unit: str, sep: str,
) -> pd.Series:
    """Loads one of synPRO's free ``.dat`` profiles (electric/room_heating/
    domestic_hot_water -- or a differently-shaped export, via
    --synpro-*-col/--synpro-sep) into an hourly-mean kW Series.

    The free set's own format: semicolon-separated, a ``#``-commented
    header block, then a data section with
    ``YYYYMMDD;hhmmss;unixtimestamp;<quantity>`` at 15-minute resolution,
    values in Watts (instantaneous, not already-integrated energy) --
    ``comment='#'`` makes ``read_csv`` skip the header block and treat the
    first uncommented line as the column names.
    """
    df = pd.read_csv(path, sep=sep, comment="#")
    if time_col not in df.columns or load_col not in df.columns:
        raise ValueError(
            f"expected columns {time_col!r} and {load_col!r} in {path}, found {list(df.columns)} "
            "-- pass --synpro-time-col/--synpro-load-col/--synpro-sep to match the actual export."
        )
    if pd.api.types.is_numeric_dtype(df[time_col]):
        index = pd.to_datetime(df[time_col], unit="s")  # unixtimestamp
    else:
        index = pd.to_datetime(df[time_col])
    series = pd.Series(df[load_col].to_numpy(dtype=float), index=index, name="synpro_kW")
    if unit in ("Wh", "W"):
        series = series / 1000.0
    elif unit not in ("kW", "kWh"):
        raise ValueError(f"unknown --synpro-unit {unit!r}")
    series = series.sort_index()
    # Instantaneous power at native (here 15-min) resolution -> hourly mean
    # power, matching buem's own hourly resolution. A plain mean (not a
    # sum) is correct for averaging power over sub-steps of an hour.
    return series.resample("h").mean()


def mean_relative_error(measured: np.ndarray, simulated: np.ndarray) -> float:
    """synPRO paper Eq. 3: mean_i(|y_i - x_i| / y_i), y=measured/reference."""
    mask = measured != 0
    return float(np.mean(np.abs(measured[mask] - simulated[mask]) / measured[mask])) * 100.0


def compare(buem_kW: pd.Series, synpro_kW: pd.Series) -> dict:
    """Aligns both series on daily means by day-of-year (robust to buem's
    weather-archive year and synPRO's export year being different calendar
    years -- see module docstring) and reports the same metrics synPRO's
    own paper uses: annual demand delta, correlation, and mean relative
    error on daily mean profiles."""
    buem_daily = buem_kW.resample("D").mean()
    synpro_daily = synpro_kW.resample("D").mean()
    buem_daily.index = buem_daily.index.dayofyear
    synpro_daily.index = synpro_daily.index.dayofyear
    # A leap-year day-of-year index can collide/duplicate against a
    # non-leap-year one past day 59 (Feb 29) -- average any such
    # duplicates away rather than silently picking one arbitrarily.
    buem_daily = buem_daily.groupby(level=0).mean()
    synpro_daily = synpro_daily.groupby(level=0).mean()
    common_index = buem_daily.index.intersection(synpro_daily.index)
    if len(common_index) == 0:
        raise ValueError("buem and synPRO series share no overlapping day-of-year values.")
    buem_aligned = buem_daily.loc[common_index]
    synpro_aligned = synpro_daily.loc[common_index]

    buem_annual_kwh = float(buem_kW.sum())
    synpro_annual_kwh = float(synpro_kW.sum())
    annual_delta_pct = (buem_annual_kwh - synpro_annual_kwh) / synpro_annual_kwh * 100.0

    correlation = float(np.corrcoef(buem_aligned.to_numpy(), synpro_aligned.to_numpy())[0, 1])
    err_pct = mean_relative_error(synpro_aligned.to_numpy(), buem_aligned.to_numpy())

    return dict(
        n_days_compared=len(common_index),
        buem_annual_kWh=round(buem_annual_kwh, 1),
        synpro_annual_kWh=round(synpro_annual_kwh, 1),
        annual_delta_pct=round(annual_delta_pct, 1),
        daily_correlation_R=round(correlation, 3),
        daily_mean_Err_pct=round(err_pct, 1),
    )


_DEFAULT_LOAD_COL = {"electricity": "P_el", "heating": "Q_htg", "dhw": "Q_dhw"}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--quantity", type=str, required=True, choices=QUANTITIES,
                        help="Which buem output / synPRO reference column to compare. "
                             "Cooling and cooking have no synPRO reference at all -- see "
                             "module docstring -- and are not offered here.")
    parser.add_argument("--synpro-dat", type=Path, required=True,
                        help="A synPRO free-profile .dat file under validation/NL/synpro/reference/ "
                             "(or any CSV/DAT export matching --synpro-time-col/--synpro-load-col/"
                             "--synpro-sep).")
    parser.add_argument("--synpro-sep", type=str, default=";")
    parser.add_argument("--synpro-time-col", type=str, default="unixtimestamp")
    parser.add_argument("--synpro-load-col", type=str, default=None,
                        help="Defaults per --quantity: P_el/Q_htg/Q_dhw.")
    parser.add_argument("--synpro-unit", type=str, default="W",
                        choices=["kWh", "kW", "Wh", "W"],
                        help="Unit of --synpro-load-col; converted to kW.")
    parser.add_argument("--label", type=str, required=True,
                        help="Household/envelope group label, e.g. 1FF/2FF/4FF or "
                             "old_building_SFH (for the report only).")
    parser.add_argument("--num-persons", type=float, required=True)
    parser.add_argument("--archetype", type=str, default=None,
                        help="occupancy archetype override, e.g. working_couple, "
                             "family_with_children. Omit to use buem's own "
                             "building-type-based default (an approximation point "
                             "for this comparison -- see module docstring).")
    parser.add_argument("--building-type", type=str, default=None,
                        help="Override the fixture's building_type (default fixture is SFH). "
                             "Matters for occupancy archetype auto-selection and DHW fixture "
                             "sizing even with the generic (non-matched) envelope -- e.g. pass "
                             "MFH for synPRO's *_multi_party_house.dat references.")
    parser.add_argument("--building-geojson", type=Path, default=None,
                        help="Real matched-envelope building to use instead of the generic "
                             "dummy fixture -- see module docstring's heating/dhw caveat.")
    parser.add_argument("--country", type=str, default="DE")
    parser.add_argument("--latitude", type=float, default=DEFAULT_LATITUDE)
    parser.add_argument("--longitude", type=float, default=DEFAULT_LONGITUDE)
    parser.add_argument("--year", type=int, default=DEFAULT_YEAR)
    parser.add_argument("--provider", type=str, default=DEFAULT_WEATHER_PROVIDER,
                        choices=["merra-2", "cosmo-rea6", "era5-land"],
                        help="Defaults to buem's own default (merra-2). synPRO's web "
                             "simulator defaults to era5-land -- pass --provider era5-land "
                             "to match it, but note (CLAUDE.md 'Weather is compulsory') "
                             "era5-land currently fails outright for Jan of some years/cells "
                             "due to an unrepaired archive boundary.")
    parser.add_argument("--n-seeds", type=int, default=10,
                        help="Number of buem runs (distinct seeds) averaged before comparing "
                             "-- see module docstring's 'Seed-averaging' section. 1 disables "
                             "averaging (single realization, noisy daily correlation).")
    parser.add_argument("--csv", type=Path, default=None, help="Append the summary row here.")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    if args.quantity != "electricity":
        logger.warning(
            "--quantity %s: the default envelope is NOT calibrated to match synPRO's German "
            "old-building/passive-house archetypes -- this run is indicative of plausibility "
            "only, not an envelope-matched comparison. Pass --building-geojson for a real one.",
            args.quantity,
        )

    logger.info(
        "Running buem (%d seed(s)): quantity=%s num_persons=%s archetype=%s country=%s "
        "(%.4f, %.4f) year=%d provider=%s",
        args.n_seeds, args.quantity, args.num_persons, args.archetype, args.country,
        args.latitude, args.longitude, args.year, args.provider,
    )
    buem_kW = run_buem_quantity_averaged(
        n_seeds=args.n_seeds, quantity=args.quantity, num_persons=args.num_persons,
        archetype=args.archetype, country=args.country, building_type=args.building_type,
        latitude=args.latitude, longitude=args.longitude, year=args.year, provider=args.provider,
        building_geojson=args.building_geojson,
    )

    logger.info("Loading synPRO reference: %s", args.synpro_dat)
    synpro_kW = load_synpro_reference(
        args.synpro_dat, time_col=args.synpro_time_col,
        load_col=args.synpro_load_col or _DEFAULT_LOAD_COL[args.quantity],
        unit=args.synpro_unit, sep=args.synpro_sep,
    )

    result = compare(buem_kW, synpro_kW)
    result["quantity"] = args.quantity
    result["label"] = args.label
    result["num_persons"] = args.num_persons
    result["archetype"] = args.archetype or "(default)"
    result["n_seeds"] = args.n_seeds

    print()
    print(f"buem {args.quantity} vs synPRO reference -- group {args.label} ({args.n_seeds} seed(s) averaged)")
    print("=" * 70)
    for key, value in result.items():
        print(f"  {key}: {value}")
    print()
    print(
        "Reference (synPRO paper, Table 3/4, 100-household group averages): correlation R "
        "typically 0.86-0.98, Err typically 2.9-16.1%. This comparison's synPRO side is a "
        "single realization, not a 100-household average -- see module docstring's "
        "'Seed-averaging' section for why exact correlation parity isn't expected even when "
        "buem is itself seed-averaged."
    )

    if args.csv is not None:
        args.csv.parent.mkdir(parents=True, exist_ok=True)
        row = pd.DataFrame([result])
        if args.csv.exists():
            existing = pd.read_csv(args.csv)
            row = pd.concat([existing, row], ignore_index=True)
        row.to_csv(args.csv, index=False)
        print(f"\nWrote {args.csv}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
